version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb"
    hostname: mongodb
    ports:
      - "27017:27017"
  app:
    image: aptheone/spring-boot-mongodb:v1.1
    container_name: "springboot"
    hostname: app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb